name: Update Repository From Production Salesforce

on:
    workflow_dispatch:
    schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 1 * * *'

jobs:
  set_environment:
    name: Set Branch Environment - ${{ github.ref_name }}
    outputs:
      github_environment: ${{ steps.setenv.outputs.github_environment }}
    runs-on: ubuntu-latest
    steps:
    - name: Setting Github Environment
      id: setenv
      run: echo "github_environment=${{ github.ref_name }}" >> "$GITHUB_OUTPUT"

  build:
    name: Update ${{ github.ref_name }} From Salesforce
    runs-on: ubuntu-latest
    needs: set_environment
    environment: ${{ needs.set_environment.outputs.github_environment }}
    permissions:
        contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
        fetch-depth: 0
        token: ${{ secrets.PAT }}
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12' 
        cache: 'pip'
    - run: pip install -r scripts/python/requirements.txt

    - name: Install Salesforce CLI
      run: |
        npm install @salesforce/cli --location=global
        nodeInstallPath=$(npm config get prefix)
        echo "$nodeInstallPath/bin" >> $GITHUB_PATH
        sf --version

    - name: Retrieve Metadata
      run: python scripts/python/update_repository_from_production.py ${{ secrets.SF_AUTH_URL }}

    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    - name: Commit Changes to ${{ github.ref_name }}
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        branch:  ${{ github.ref_name }}
        commit_message: Automated  ${{ github.ref_name }} Sync - ${{ steps.date.outputs.date }}
        push_options: '--force'
